version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-prod
    image: "${API_IMAGE}"
    ports:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_SERVICE_URL=${REACT_APP_SERVICE_URL}
    image: "${CLIENT_IMAGE}"
    ports:
      - 3000
    depends_on:
      - api
